services:
  health-information-system:
    # container_name: health-information-system
    image: health-information-system
    build: .  
    ports:
      - 8081-9000:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  mysql-server:
    image: mysql
    container_name: mysql-server
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=health_information_system