services:
  health-information-system:
    container_name: health-information-system
    image: health-information-system
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_HOST_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}
  mysql-server:
    container_name: mysql_server
    image: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - C:/Users/ITCompliance/Desktop/Docker/mysql_data:/var/lib/mysql
